backend:
  name: git-gateway
  branch: main
  
media_folder: "client/public/assets"
public_folder: "/assets"

locale: 'en'
show_preview_links: true
display_url: https://thegoanwedding.com
logo_url: https://thegoanwedding.com/assets/logo.png

collections:
  - name: "checklists"
    label: "Planning Checklists"
    label_singular: "Checklist"
    folder: "content/checklists"
    create: true
    slug: "{{slug}}"
    preview_path: "/checklists/{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Enter a descriptive title for the checklist"
      - label: "Description"
        name: "description"
        widget: "text"
        required: true
        hint: "Brief description of what this checklist covers"
      - label: "Category"
        name: "category"
        widget: "select"
        required: true
        options:
          - label: "Wedding Planning"
            value: "wedding-planning"
          - label: "Vendor Selection"
            value: "vendor-selection"
          - label: "Budget Management"
            value: "budget-management"
          - label: "Timeline Planning"
            value: "timeline-planning"
          - label: "Venue Selection"
            value: "venue-selection"
          - label: "Photography & Video"
            value: "photography-video"
          - label: "Catering & Menu"
            value: "catering-menu"
          - label: "Decorations & Flowers"
            value: "decorations-flowers"
          - label: "Traditional Ceremonies"
            value: "traditional-ceremonies"
      - label: "Difficulty Level"
        name: "difficulty"
        widget: "select"
        required: true
        options:
          - label: "Beginner"
            value: "beginner"
          - label: "Intermediate"
            value: "intermediate"
          - label: "Advanced"
            value: "advanced"
      - label: "Estimated Time"
        name: "estimatedTime"
        widget: "string"
        required: true
        hint: "e.g., '2 hours', '1 week', '3 months'"
      - label: "Featured Image"
        name: "featuredImage"
        widget: "image"
        required: false
        hint: "Upload a relevant image for this checklist"
      - label: "Introduction"
        name: "introduction"
        widget: "markdown"
        required: false
        hint: "Optional introduction text that appears before the checklist"
      - label: "Steps"
        name: "steps"
        widget: "list"
        required: true
        min: 1
        fields:
          - label: "Step Title"
            name: "title"
            widget: "string"
            required: true
          - label: "Step Details"
            name: "details"
            widget: "markdown"
            required: true
          - label: "Priority"
            name: "priority"
            widget: "select"
            required: true
            default: "medium"
            options:
              - label: "High"
                value: "high"
              - label: "Medium"
                value: "medium"
              - label: "Low"
                value: "low"
          - label: "Timeline"
            name: "timeline"
            widget: "string"
            required: false
            hint: "When should this step be completed? e.g., '12 months before', '1 week before'"
          - label: "Estimated Cost"
            name: "estimatedCost"
            widget: "string"
            required: false
            hint: "Approximate cost for this step (optional)"
          - label: "Tips"
            name: "tips"
            widget: "list"
            required: false
            field:
              label: "Tip"
              name: "tip"
              widget: "string"
          - label: "Related Vendors"
            name: "relatedVendors"
            widget: "list"
            required: false
            field:
              label: "Vendor Category"
              name: "vendorCategory"
              widget: "string"
              hint: "e.g., 'photographers', 'venues', 'caterers'"
      - label: "Conclusion"
        name: "conclusion"
        widget: "markdown"
        required: false
        hint: "Optional conclusion or final tips"
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field:
          label: "Tag"
          name: "tag"
          widget: "string"
      - label: "SEO Title"
        name: "seoTitle"
        widget: "string"
        required: false
        hint: "Custom title for search engines (optional)"
      - label: "SEO Description"
        name: "seoDescription"
        widget: "text"
        required: false
        hint: "Meta description for search engines (optional)"
      - label: "Published"
        name: "published"
        widget: "boolean"
        default: false
        hint: "Check to make this checklist visible on the website"
      - label: "Created Date"
        name: "createdDate"
        widget: "datetime"
        default: ""
        hint: "When this checklist was created"
      - label: "Last Updated"
        name: "lastUpdated"
        widget: "datetime"
        default: ""
        hint: "When this checklist was last modified"

  - name: "guides"
    label: "Vendor Guides"
    label_singular: "Guide"
    folder: "content/guides"
    create: true
    slug: "{{slug}}"
    preview_path: "/guides/{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Description"
        name: "description"
        widget: "text"
        required: true
      - label: "Vendor Category"
        name: "vendorCategory"
        widget: "select"
        required: true
        options:
          - label: "Photographers"
            value: "photographers"
          - label: "Venues"
            value: "venues"
          - label: "Caterers"
            value: "caterers"
          - label: "Decorators"
            value: "decorators"
          - label: "Makeup Artists"
            value: "makeup-artists"
          - label: "Bridal Wear"
            value: "bridal-wear"
          - label: "Groom Wear"
            value: "groom-wear"
          - label: "Jewelry"
            value: "jewelry"
          - label: "Music & DJ"
            value: "music-dj"
          - label: "Transportation"
            value: "transportation"
          - label: "Wedding Planners"
            value: "wedding-planners"
          - label: "Florists"
            value: "florists"
      - label: "Guide Type"
        name: "guideType"
        widget: "select"
        required: true
        options:
          - label: "Selection Guide"
            value: "selection"
          - label: "Questions to Ask"
            value: "questions"
          - label: "Budget Guide"
            value: "budget"
          - label: "Timeline Guide"
            value: "timeline"
          - label: "Comparison Guide"
            value: "comparison"
      - label: "Featured Image"
        name: "featuredImage"
        widget: "image"
        required: false
      - label: "Content"
        name: "body"
        widget: "markdown"
        required: true
      - label: "Key Points"
        name: "keyPoints"
        widget: "list"
        required: false
        field:
          label: "Key Point"
          name: "point"
          widget: "string"
      - label: "Questions to Ask Vendors"
        name: "questionsToAsk"
        widget: "list"
        required: false
        fields:
          - label: "Question"
            name: "question"
            widget: "string"
            required: true
          - label: "Why Important"
            name: "importance"
            widget: "text"
            required: false
          - label: "Category"
            name: "category"
            widget: "select"
            required: false
            options:
              - "Pricing"
              - "Experience"
              - "Availability"
              - "Services"
              - "Portfolio"
              - "Logistics"
              - "Contract"
      - label: "Budget Ranges"
        name: "budgetRanges"
        widget: "object"
        required: false
        fields:
          - label: "Budget Low (₹)"
            name: "low"
            widget: "number"
            required: false
          - label: "Budget Medium (₹)"
            name: "medium"
            widget: "number"
            required: false
          - label: "Budget High (₹)"
            name: "high"
            widget: "number"
            required: false
          - label: "Budget Notes"
            name: "notes"
            widget: "text"
            required: false
      - label: "Timeline Recommendations"
        name: "timeline"
        widget: "list"
        required: false
        fields:
          - label: "Task"
            name: "task"
            widget: "string"
            required: true
          - label: "When"
            name: "when"
            widget: "string"
            required: true
            hint: "e.g., '12 months before', '2 weeks before'"
          - label: "Priority"
            name: "priority"
            widget: "select"
            required: true
            options:
              - "High"
              - "Medium"
              - "Low"
      - label: "Red Flags"
        name: "redFlags"
        widget: "list"
        required: false
        field:
          label: "Red Flag"
          name: "flag"
          widget: "string"
      - label: "Pro Tips"
        name: "proTips"
        widget: "list"
        required: false
        field:
          label: "Pro Tip"
          name: "tip"
          widget: "string"
      - label: "Related Checklists"
        name: "relatedChecklists"
        widget: "list"
        required: false
        field:
          label: "Checklist Slug"
          name: "checklistSlug"
          widget: "string"
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field:
          label: "Tag"
          name: "tag"
          widget: "string"
      - label: "Published"
        name: "published"
        widget: "boolean"
        default: false
      - label: "Created Date"
        name: "createdDate"
        widget: "datetime"
        default: ""
      - label: "Last Updated"
        name: "lastUpdated"
        widget: "datetime"
        default: ""

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Checklist Settings"
        name: "checklistSettings"
        file: "content/settings/checklist-settings.yml"
        fields:
          - label: "Featured Checklists"
            name: "featuredChecklists"
            widget: "list"
            max: 6
            field:
              label: "Checklist Slug"
              name: "slug"
              widget: "string"
          - label: "Categories Display Order"
            name: "categoriesOrder"
            widget: "list"
            field:
              label: "Category"
              name: "category"
              widget: "string"
          - label: "Default Checklist Image"
            name: "defaultImage"
            widget: "image"
            required: false