backend:
  name: git-gateway
  branch: main

# Admin-only configuration
publish_mode: editorial_workflow

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "vendors"
    label: "Vendors"
    folder: "content/vendors"
    create: false  # Admin-only: prevent public creation
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Photography", "Videography", "Venue", "Catering", "Decoration", "Music", "Transport", "Beauty", "Other"] }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Phone", name: "phone", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "WhatsApp", name: "whatsapp", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Address", name: "address", widget: "string" }
      - { label: "Website", name: "website", widget: "string" }
      - { label: "Instagram", name: "instagram", widget: "string" }
      - { label: "YouTube", name: "youtube", widget: "string" }
      - { label: "Facebook", name: "facebook", widget: "string" }
      - { label: "Profile Image", name: "profileImage", widget: "image" }
      - { label: "Cover Image", name: "coverImage", widget: "image" }
      - { label: "Gallery", name: "gallery", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
      - { label: "Services", name: "services", widget: "list", field: { label: "Service", name: "service", widget: "string" } }
      - { label: "Price Range", name: "priceRange", widget: "select", options: ["$", "$$", "$$$", "$$$$"] }
      - { label: "Featured", name: "featured", widget: "boolean" }
      - { label: "Verified", name: "verified", widget: "boolean" }

  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" } }
      - { label: "Published", name: "published", widget: "boolean" }

